version: "3"
services:
  server-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - awesome
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOSTNAME=postgres
  postgres:
    build:
        context: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=postgres
    restart: always
    networks:
      - awesome
networks:
    awesome:
        driver: bridge 